services:
  db:
    image: postgres:16
    container_name: meditrack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meditrack
    ports:
      - "5432:5432"
    volumes:
      - meditrack_postgres_data:/var/lib/postgresql/data

volumes:
  meditrack_postgres_data: